export interface AnesthesiaDrug {
  id: string
  user_id: string | null
  name: string
  category: string
  mechanism_of_action: string
  pharmacokinetics: string
  pharmacodynamics: string
  onset_of_action: string
  duration_of_action: string
  induction_dose: string
  maintenance_dose: string
  side_effects: string
  clinical_considerations: string
  contraindications?: string
  infusion_guidelines?: string
  is_high_alert: boolean
  created_at?: string
  updated_at?: string
}

export const builtInDrugs: AnesthesiaDrug[] = [
  {
    id: "builtin-propofol",
    user_id: null,
    name: "Propofol",
    category: "Induction Agents",
    mechanism_of_action: "Facilitates inhibitory neurotransmission mediated by GABAA receptors. Binding to GABAA receptors activates chloride channels, causing hyperpolarization of the postsynaptic membrane and CNS depression.",
    pharmacokinetics: "Highly lipid-soluble. Rapid distribution (t1/2 alpha = 2-8 mins). Rapidly metabolized by the liver (glucuronidation) and extrahepatically (lungs). High clearance rate exceeding hepatic blood flow. Elimination half-life is 3-12 hours.",
    pharmacodynamics: "Dose-dependent decrease in systemic vascular resistance (SVR) and venous return, leading to hypotension. Mild respiratory depression (apnea). Decreases cerebral metabolic rate of oxygen (CMRO2), cerebral blood flow (CBF), and intracranial pressure (ICP).",
    onset_of_action: "30 - 40 seconds",
    duration_of_action: "3 - 8 minutes",
    induction_dose: "1.5 - 2.5 mg/kg IV",
    maintenance_dose: "100 - 200 mcg/kg/min IV infusion (sedation: 25 - 75 mcg/kg/min)",
    side_effects: "Hypotension, bradycardia, pain on injection, apnea, myoclonus, Propofol Infusion Syndrome (PRIS) with prolonged high-dose infusions (>48h, >4 mg/kg/hr or 67 mcg/kg/min).",
    clinical_considerations: "Avoid in patients with severe egg/soy allergies (lipid emulsion formulation). Cardio-depressant: use with caution in hypovolemic or cardiac-compromised patients. Strict aseptic technique required (lipid emulsion supports bacterial growth). Antiemetic properties at low doses.",
    contraindications: "Hypersensitivity to propofol, egg, or soy. Acute decompensated heart failure.",
    infusion_guidelines: "Dilute in D5W if necessary; use dedicated IV lines. Change tubing every 12 hours.",
    is_high_alert: true,
  },
  {
    id: "builtin-ketamine",
    user_id: null,
    name: "Ketamine",
    category: "Induction Agents / Analgesics",
    mechanism_of_action: "Non-competitive antagonist at the NMDA receptor. Blocks glutamate binding, disrupting association pathways between the limbic system and thalamo-neocortical system (dissociative anesthesia).",
    pharmacokinetics: "Highly lipid-soluble. Rapid onset. Hepatic metabolism via CYP450 (N-demethylation) to norketamine (active metabolite, 1/3-1/5 potency). Excreted in urine. Elimination half-life is 2-3 hours.",
    pharmacodynamics: "Sympathomimetic: increases heart rate, blood pressure, and cardiac output. Preserves airway reflexes and respiratory drive. Bronchodilator. Increases CMRO2, CBF, and ICP (mitigated by controlled ventilation and co-administration of GABA agonists).",
    onset_of_action: "30 - 60 seconds IV; 3 - 4 minutes IM",
    duration_of_action: "10 - 20 minutes IV; 60 - 120 minutes IM",
    induction_dose: "1.0 - 2.0 mg/kg IV; 4.0 - 10.0 mg/kg IM",
    maintenance_dose: "0.5 - 2.0 mg/kg/hr IV infusion (sub-anesthetic analgesia: 0.1 - 0.5 mg/kg/hr)",
    side_effects: "Emergence delirium, hallucinations, vivid dreams, tachycardia, hypertension, hypersalivation, increased intraocular pressure.",
    clinical_considerations: "Co-administer benzodiazepine (e.g. Midazolam) to decrease incidence of emergence delirium. Excellent choice for asthmatics (bronchodilation) and hemodynamically unstable patients (septic shock, hypovolemia). Avoid as sole agent in severe ischemic heart disease.",
    contraindications: "Conditions where increased blood pressure would be hazardous (e.g. severe uncontrolled hypertension, aneurysm). Severe pre-eclampsia.",
    infusion_guidelines: "Compatible with NS and D5W. Titrate slowly for sub-anesthetic analgesia.",
    is_high_alert: true,
  },
  {
    id: "builtin-fentanyl",
    user_id: null,
    name: "Fentanyl",
    category: "Opioids / Analgesics",
    mechanism_of_action: "Selective agonist at the mu-opioid receptor. Inhibits adenyl cyclase, decreases intracellular cAMP, blocks calcium channels (inhibiting neurotransmitter release), and opens potassium channels (hyperpolarization).",
    pharmacokinetics: "Highly lipophilic. Rapid redistribution from brain to inactive tissues (termination of action after bolus). Metabolized by liver (CYP3A4) to inactive metabolite (norfentanyl). Excreted renally. Elimination half-life is 3-4 hours.",
    pharmacodynamics: "Minimal cardiovascular depression (hemodynamically stable). Dose-dependent respiratory depression. Decreases heart rate (vagal stimulation). Pupillary constriction (miosis). Decreases MAC of inhalation agents.",
    onset_of_action: "1 - 2 minutes IV",
    duration_of_action: "30 - 60 minutes IV",
    induction_dose: "1.0 - 5.0 mcg/kg IV (higher doses up to 20-50 mcg/kg for cardiac surgery)",
    maintenance_dose: "1.0 - 3.0 mcg/kg/hr IV infusion or boluses of 25-100 mcg IV as needed",
    side_effects: "Respiratory depression, bradycardia, chest wall rigidity ('woody chest' with rapid high-dose IV bolus), nausea/vomiting, pruritus, urinary retention.",
    clinical_considerations: "Much more potent than morphine (100 times). Rigidity can make ventilation impossible; reverse with neuromuscular blockers. Synergistic respiratory depression when combined with benzodiazepines or propofol.",
    contraindications: "Hypersensitivity to fentanyl. Acute respiratory depression without mechanical ventilation.",
    infusion_guidelines: "Dilute in NS or D5W. Infusions require continuous monitoring of pulse oximetry and capnography.",
    is_high_alert: true,
  },
  {
    id: "builtin-rocuronium",
    user_id: null,
    name: "Rocuronium",
    category: "Neuromuscular Blockers",
    mechanism_of_action: "Non-depolarizing neuromuscular blocker. Competitively antagonist at nicotinic acetylcholine receptors at the motor endplate, preventing acetylcholine from binding and causing muscle contraction.",
    pharmacokinetics: "Hydrophilic. Not metabolized. Cleared primarily by the liver (biliary excretion 70%) and secondarily by kidneys (30%). Elimination half-life is 1.5 - 2 hours. Action prolonged in liver failure.",
    pharmacodynamics: "Produces flaccid skeletal muscle paralysis. Airway muscles and diaphragm are paralyzed. No cardiovascular effects at standard doses.",
    onset_of_action: "60 - 90 seconds (rapid onset at 1.2 mg/kg, suitable for RSI)",
    duration_of_action: "30 - 60 minutes",
    induction_dose: "0.6 mg/kg IV for standard intubation; 1.2 mg/kg IV for Rapid Sequence Induction (RSI)",
    maintenance_dose: "0.1 - 0.2 mg/kg IV bolus or 5 - 12 mcg/kg/min IV infusion",
    side_effects: "Prolonged neuromuscular blockade, anaphylaxis (rare but most common among non-depolarizing blockers), transient tachycardia.",
    clinical_considerations: "Ensure adequate depth of anesthesia/sedation before administration (paralysis without sedation is traumatic). Monitor neuromuscular blockade using a Train-of-Four (TOF) monitor. Reversible with Sugammadex or Neostigmine/Glycopyrrolate.",
    contraindications: "Hypersensitivity to rocuronium or bromide. Previous severe anaphylactic reaction.",
    infusion_guidelines: "Compatible with NS and D5W. Monitor TOF frequently.",
    is_high_alert: true,
  },
  {
    id: "builtin-succinylcholine",
    user_id: null,
    name: "Succinylcholine",
    category: "Neuromuscular Blockers",
    mechanism_of_action: "Depolarizing neuromuscular blocker. Binds to nicotinic acetylcholine receptors, causing prolonged depolarization of the motor endplate, resulting in fasciculations followed by flaccid muscle paralysis.",
    pharmacokinetics: "Rapidly hydrolyzed by plasma cholinesterase (pseudocholinesterase) in the blood. Very short half-life (< 1 min). Only a small fraction reaches the neuromuscular junction.",
    pharmacodynamics: "Rapid skeletal muscle paralysis. Causes transient muscle fasciculations. May cause bradycardia (especially in children or with second dose) due to muscarinic stimulation.",
    onset_of_action: "30 - 60 seconds",
    duration_of_action: "5 - 10 minutes",
    induction_dose: "1.0 - 1.5 mg/kg IV; 3.0 - 4.0 mg/kg IM (max 150 mg)",
    maintenance_dose: "Rarely used as continuous infusion due to risk of Phase II block (0.5 - 10 mg/min)",
    side_effects: "Hyperkalemia (increases serum K+ by 0.5 mEq/L), muscle fasciculations, myalgia, increased intragastric/intraocular pressure, bradycardia, Malignant Hyperthermia trigger.",
    clinical_considerations: "Drug of choice for emergency airway management (RSI) due to rapid onset and short duration. Contraindicated in burns, massive trauma, upper motor neuron lesions, and muscular dystrophy due to risk of life-threatening hyperkalemia. Avoid in pseudocholinesterase deficiency.",
    contraindications: "History of malignant hyperthermia, skeletal muscle myopathies, major burns (>48h old), denervation injury, severe hyperkalemia.",
    infusion_guidelines: "Usually given only as single boluses. Keep refrigerated.",
    is_high_alert: true,
  },
  {
    id: "builtin-etomidate",
    user_id: null,
    name: "Etomidate",
    category: "Induction Agents",
    mechanism_of_action: "GABAA receptor agonist. Enhances the effects of GABA by binding to specific sites on GABAA receptors, increasing chloride conductance and causing neural hyperpolarization.",
    pharmacokinetics: "Rapid onset and short duration due to rapid redistribution from brain. Hydrolyzed in liver by esterases to inactive carboxylic acid metabolite. Excreted renally. Elimination half-life is 2-5 hours.",
    pharmacodynamics: "Excellent cardiovascular stability (minimal change in HR, BP, CO). Mild respiratory depression. Decreases CMRO2, CBF, and ICP. Transiently suppresses adrenal steroidogenesis.",
    onset_of_action: "30 - 60 seconds",
    duration_of_action: "3 - 12 minutes",
    induction_dose: "0.2 - 0.3 mg/kg IV",
    maintenance_dose: "0.01 - 0.02 mg/kg/min IV infusion (rarely used for maintenance due to adrenal suppression)",
    side_effects: "Myoclonus (involuntary muscle movements), pain on injection, transient adrenocortical suppression (inhibits 11-beta-hydroxylase for 5-24h), nausea and vomiting.",
    clinical_considerations: "Ideal induction agent for hemodynamically unstable patients, cardiovascular disease, or severe hypovolemia. Myoclonus can be mitigated by premedication with midazolam or fentanyl. Avoid in sepsis due to adrenal suppression.",
    contraindications: "Hypersensitivity to etomidate. Sepsis or adrenal insufficiency.",
    infusion_guidelines: "Usually administered as a single IV bolus. Avoid prolonged infusions.",
    is_high_alert: false,
  },
  {
    id: "builtin-neostigmine",
    user_id: null,
    name: "Neostigmine",
    category: "Reversals / Anticholinesterases",
    mechanism_of_action: "Reversible acetylcholinesterase inhibitor. Binds to acetylcholinesterase, preventing the hydrolysis of acetylcholine. This increases acetylcholine concentration at the neuromuscular junction, outcompeting non-depolarizing muscle relaxants.",
    pharmacokinetics: "Quaternary ammonium compound (poor lipid solubility, does not cross blood-brain barrier). Metabolized by liver microsomal enzymes and hydrolyzed by cholinesterase. Excreted renally (elimination prolonged in renal failure). Elimination half-life is 50-90 minutes.",
    pharmacodynamics: "Reverses neuromuscular blockade. Cholinergic side effects: bradycardia, bronchoconstriction, increased salivation, pupillary constriction (miosis), increased bowel motility.",
    onset_of_action: "7 - 11 minutes (slow onset, requires time to accumulate acetylcholine)",
    duration_of_action: "60 - 120 minutes",
    induction_dose: "0.03 - 0.07 mg/kg IV (max 5 mg)",
    maintenance_dose: "Not applicable",
    side_effects: "Bradycardia, asystole, bronchospasm, hypersalivation, diarrhea, abdominal cramping, nausea/vomiting.",
    clinical_considerations: "Must be co-administered with an anticholinergic (usually Glycopyrrolate or Atropine) to block muscarinic side effects (bradycardia, salivation). Verify return of twitch response (at least 1-2 twitches on TOF) before administration; ineffective against deep blockade.",
    contraindications: "Mechanical intestinal or urinary tract obstruction. Peritonitis.",
    infusion_guidelines: "Administer slowly. Always give alongside glycopyrrolate or atropine.",
    is_high_alert: false,
  },
  {
    id: "builtin-sugammadex",
    user_id: null,
    name: "Sugammadex",
    category: "Reversals",
    mechanism_of_action: "Selective relaxant binding agent (SRBA). Encapsulates non-depolarizing neuromuscular blocking agents rocuronium or vecuronium in a 1:1 ratio, preventing them from binding to nicotinic receptors and rapidly reversing blockade.",
    pharmacokinetics: "Water-soluble modified gamma-cyclodextrin. Not metabolized. Cleared exclusively by the kidneys as an intact complex. Elimination half-life is 1.5 - 2.5 hours.",
    pharmacodynamics: "Rapidly and completely reverses neuromuscular blockade. No cholinergic side effects (does not affect acetylcholinesterase). Minimal cardiovascular effects.",
    onset_of_action: "1.5 - 3 minutes (extremely rapid compared to neostigmine)",
    duration_of_action: "Not applicable",
    induction_dose: "2.0 mg/kg IV for moderate block (reappearance of T2); 4.0 mg/kg IV for deep block (1-2 post-tetanic counts); 16.0 mg/kg IV for immediate reversal (3 mins after rocuronium 1.2 mg/kg)",
    maintenance_dose: "Not applicable",
    side_effects: "Anaphylaxis (rare, ~0.3%), transient bradycardia, hypersensitivity reactions, coagulation parameter changes (transient increase in aPTT/PT).",
    clinical_considerations: "No need to co-administer anticholinergics like atropine. Rocuronium/sugammadex complex is excreted renally; use with caution in severe renal impairment (e.g. GFR <30). Can encapsulate oral contraceptives, reducing their efficacy (advise patients to use backup contraception for 7 days).",
    contraindications: "Severe renal impairment (not recommended). Hypersensitivity to sugammadex.",
    infusion_guidelines: "Administer as a rapid IV bolus. Incompatible with standard drug lines; flush line before and after administration.",
    is_high_alert: false,
  },
  {
    id: "builtin-atropine",
    user_id: null,
    name: "Atropine",
    category: "Anticholinergics / Emergency",
    mechanism_of_action: "Competitive antagonist at muscarinic acetylcholine receptors. Blocks parasympathetic acetylcholine action, leading to increased heart rate and decreased secretions.",
    pharmacokinetics: "Rapidly absorbed and distributed. Crossing the blood-brain barrier (tertiary amine). Partially metabolized by liver. Excreted renally. Elimination half-life is 2 - 4 hours.",
    pharmacodynamics: "Increases heart rate (positive chronotropic effect), speeds AV conduction. Decreases salivary and bronchial secretions. Bronchodilator. Causes pupillary dilation (mydriasis) and cycloplegia.",
    onset_of_action: "30 - 60 seconds IV; 15 - 30 minutes IM",
    duration_of_action: "1 - 2 hours (cardiac); up to 4 hours (secretions)",
    induction_dose: "0.5 - 1.0 mg IV for bradycardia (repeat every 3-5 mins, max 3 mg or 0.04 mg/kg)",
    maintenance_dose: "Not applicable",
    side_effects: "Tachycardia, palpitations, dry mouth, blurred vision, urinary retention, flushing, confusion, central anticholinergic syndrome (hallucinations, delirium).",
    clinical_considerations: "First-line drug for symptomatic bradycardia. Low doses (<0.5 mg) can cause paradoxical bradycardia due to central/peripheral presynaptic muscarinic blocking. Use with caution in coronary artery disease (tachycardia increases oxygen demand).",
    contraindications: "Angle-closure glaucoma. Pyloric stenosis. Thyrotoxicosis.",
    infusion_guidelines: "Administer rapid IV push. Incompatible with alkaline solutions.",
    is_high_alert: false,
  },
  {
    id: "builtin-norepinephrine",
    user_id: null,
    name: "Norepinephrine",
    category: "Vasopressors / Cardiovascular",
    mechanism_of_action: "Direct-acting sympathomimetic. Potent alpha-1 receptor agonist, causing peripheral vasoconstriction. Weak beta-1 agonist, causing mild increase in heart rate and myocardial contractility.",
    pharmacokinetics: "Rapid onset, extremely short duration of action. Rapidly metabolized in liver and other tissues by MAO and COMT. Excreted in urine. Half-life is 1 - 2 minutes.",
    pharmacodynamics: "Increases systolic and diastolic blood pressure, increases systemic vascular resistance (SVR). Reflex bradycardia may occur in response to increased blood pressure.",
    onset_of_action: "1 - 2 minutes IV",
    duration_of_action: "2 - 10 minutes (requires continuous infusion)",
    induction_dose: "0.05 - 0.15 mcg/kg/min IV titration for shock states",
    maintenance_dose: "0.01 - 1.0 mcg/kg/min IV infusion (titrated to MAP target)",
    side_effects: "Arrhythmias, myocardial ischemia, severe peripheral vasoconstriction (limb ischemia), extravasation necrosis, headache, anxiety.",
    clinical_considerations: "First-line vasopressor for septic shock and vasodilatory shock. Administer through a central venous catheter to prevent extravasation and tissue necrosis. If extravasation occurs, treat with phentolamine.",
    contraindications: "Hypotension from uncorrected blood volume deficits. Mesenteric or peripheral vascular thrombosis.",
    infusion_guidelines: "Dilute in D5W or D5NS to prevent oxidation. Run via dedicated infusion pump, monitor arterial blood pressure closely.",
    is_high_alert: true,
  },
]
